package com.hod.pojo;
// Generated Mar 13, 2013 4:36:39 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hod2000Price generated by hbm2java
 */
public class Hod2000Price  implements java.io.Serializable {


     private Integer pid  ;
     private String pname  ;
     private Integer ptype  ;
     private Integer pstatus  ;
     private Date pstartTime;
     private Set<Hod2000PriceDetail> hod2000PriceDetails   = new HashSet<Hod2000PriceDetail>(0);

    public Hod2000Price() {
    }

	
    public Hod2000Price(Integer pid) {
        this.pid = pid;
    }
    public Hod2000Price(Integer pid, String pname, Integer ptype, Integer pstatus, Date pstartTime,Set<Hod2000PriceDetail> hod2000PriceDetails) {
       this.pid = pid;
       this.pname = pname;
       this.ptype = ptype;
       this.pstatus = pstatus;
       this.pstartTime=pstartTime;
       this.hod2000PriceDetails = hod2000PriceDetails;
    }
   
    public Integer getPid() {
        return this.pid;
    }
    
    public void setPid(Integer pid) {
        this.pid = pid;
    }
    public String getPname() {
        return this.pname;
    }
    
    public void setPname(String pname) {
        this.pname = pname;
    }
    public Integer getPtype() {
        return this.ptype;
    }
    
    public void setPtype(Integer ptype) {
        this.ptype = ptype;
    }
    public Integer getPstatus() {
        return this.pstatus;
    }
    
    public void setPstatus(Integer pstatus) {
        this.pstatus = pstatus;
    }
    public Set<Hod2000PriceDetail> getHod2000PriceDetails() {
        return this.hod2000PriceDetails;
    }
    
    public void setHod2000PriceDetails(Set<Hod2000PriceDetail> hod2000PriceDetails) {
        this.hod2000PriceDetails = hod2000PriceDetails;
    }


	public Date getPstartTime() {
		return pstartTime;
	}


	public void setPstartTime(Date pstartTime) {
		this.pstartTime = pstartTime;
	}
}


