package com.hod.pojo;

import java.util.Date;

// Generated Feb 27, 2013 9:09:57 AM by Hibernate Tools 3.2.2.GA



/**
 * Hod2000Meter generated by hbm2java
 */
public class Hod2000Meter  implements java.io.Serializable {


     private Integer meterId  ;
     private String meterName  ;
     private Integer meterIndex;
     private String meterCaliber  ;
     private Double meterInit  ;
     private String meterPort  ;
     private String meterBaudrate  ;
     private String meterParent  ;
     private String meterPosition  ;
     private String meterPositionName  ;
     private Integer valveStatus;
     private Integer batteryStatus;
     private Integer isOnline;
     private Integer meterAble;
     private Date changeMeterTime;
     private String valveId;
     private Integer meterStyle;
     private Integer eepromStatus;
     private Integer flowsensorStatus;
     private Integer tepdownStatus;
     private Integer tepupStatus;
     private String changeValue;
     private Hod2000Room hod2000Room  = new Hod2000Room();
     private Hod2000Concentrator hod2000Concentrator  = new Hod2000Concentrator();
     private Hod2000MeterType hod2000MeterType=new Hod2000MeterType();

    public Hod2000Meter() {
    }

	
    public Hod2000Meter(Integer meterId) {
        this.meterId = meterId;
    }
    public Hod2000Meter(Integer meterId,Integer valveStatus,Integer batteryStatus,Integer isOnline, String meterName,Integer meterIndex, String meterCaliber, Double meterInit, String meterPort, String meterBaudrate, String meterParent, String meterPosition, String meterPositionName,Integer meterAble,Date changeMeterTime,String valveId,Integer meterStyle,Integer eepromStatus,Integer flowsensorStatus,Integer tepdownStatus,Integer tepupStatus,String changeValue, Hod2000Room hod2000Room, Hod2000Concentrator hod2000Concentrator,Hod2000MeterType hod2000MeterType) {
       this.meterId = meterId;
       this.meterName = meterName;
       this.meterIndex=meterIndex;
       this.meterCaliber = meterCaliber;
       this.meterInit = meterInit;
       this.meterPort = meterPort;
       this.meterBaudrate = meterBaudrate;
       this.meterParent = meterParent;
       this.meterPosition = meterPosition;
       this.meterPositionName = meterPositionName;
       this.meterAble=meterAble;
       this.changeMeterTime=changeMeterTime;
       this.valveId=valveId;
       this.meterStyle=meterStyle;
       this.eepromStatus=eepromStatus;
       this.flowsensorStatus=flowsensorStatus;
       this.tepdownStatus=tepdownStatus;
       this.tepupStatus=tepupStatus;
       this.hod2000Room = hod2000Room;
       this.hod2000Concentrator = hod2000Concentrator;
       this.hod2000MeterType=hod2000MeterType;
       this.batteryStatus=batteryStatus;
       this.valveStatus=valveStatus;
       this.isOnline=isOnline;
       this.changeValue=changeValue;
    }
   
    public Integer getMeterAble() {
		return meterAble;
	}


	public void setMeterAble(Integer meterAble) {
		this.meterAble = meterAble;
	}


	public Date getChangeMeterTime() {
		return changeMeterTime;
	}


	public void setChangeMeterTime(Date changeMeterTime) {
		this.changeMeterTime = changeMeterTime;
	}


	public Integer getMeterId() {
        return this.meterId;
    }
    
    public void setMeterId(Integer meterId) {
        this.meterId = meterId;
    }
    public String getMeterName() {
        return this.meterName;
    }
    
    public void setMeterName(String meterName) {
        this.meterName = meterName;
    }
    public String getMeterCaliber() {
        return this.meterCaliber;
    }
    
    public void setMeterCaliber(String meterCaliber) {
        this.meterCaliber = meterCaliber;
    }
    public Double getMeterInit() {
        return this.meterInit;
    }
    
    public void setMeterInit(Double meterInit) {
        this.meterInit = meterInit;
    }
    public String getMeterPort() {
        return this.meterPort;
    }
    
    public void setMeterPort(String meterPort) {
        this.meterPort = meterPort;
    }
    public String getMeterBaudrate() {
        return this.meterBaudrate;
    }
    
    public void setMeterBaudrate(String meterBaudrate) {
        this.meterBaudrate = meterBaudrate;
    }
    public String getMeterParent() {
        return this.meterParent;
    }
    
    public void setMeterParent(String meterParent) {
        this.meterParent = meterParent;
    }
    public String getMeterPosition() {
        return this.meterPosition;
    }
    
    public void setMeterPosition(String meterPosition) {
        this.meterPosition = meterPosition;
    }
    public String getMeterPositionName() {
        return this.meterPositionName;
    }
    
    public void setMeterPositionName(String meterPositionName) {
        this.meterPositionName = meterPositionName;
    }
    public Hod2000Room getHod2000Room() {
        return this.hod2000Room;
    }
    
    public void setHod2000Room(Hod2000Room hod2000Room) {
        this.hod2000Room = hod2000Room;
    }
    public Hod2000Concentrator getHod2000Concentrator() {
        return this.hod2000Concentrator;
    }
    
    public void setHod2000Concentrator(Hod2000Concentrator hod2000Concentrator) {
        this.hod2000Concentrator = hod2000Concentrator;
    }

	public Integer getMeterIndex() {
		return meterIndex;
	}

	public void setMeterIndex(Integer meterIndex) {
		this.meterIndex = meterIndex;
	}

	public Hod2000MeterType getHod2000MeterType() {
		return hod2000MeterType;
	}

	public void setHod2000MeterType(Hod2000MeterType hod2000MeterType) {
		this.hod2000MeterType = hod2000MeterType;
	}

	public Integer getValveStatus() {
		return valveStatus;
	}

	public void setValveStatus(Integer valveStatus) {
		this.valveStatus = valveStatus;
	}

	public Integer getBatteryStatus() {
		return batteryStatus;
	}

	public void setBatteryStatus(Integer batteryStatus) {
		this.batteryStatus = batteryStatus;
	}

	public Integer getIsOnline() {
		return isOnline;
	}

	public void setIsOnline(Integer isOnline) {
		this.isOnline = isOnline;
	}

	public String getValveId() {
		return valveId;
	}

	public void setValveId(String valveId) {
		this.valveId = valveId;
	}

	public void setMeterStyle(Integer meterStyle) {
		this.meterStyle = meterStyle;
	}
	
	public Integer getMeterStyle() {
		return meterStyle;
	}

	public Integer getEepromStatus() {
		return eepromStatus;
	}

	public void setEepromStatus(Integer eepromStatus) {
		this.eepromStatus = eepromStatus;
	}

	public Integer getFlowsensorStatus() {
		return flowsensorStatus;
	}

	public void setFlowsensorStatus(Integer flowsensorStatus) {
		this.flowsensorStatus = flowsensorStatus;
	}

	public Integer getTepdownStatus() {
		return tepdownStatus;
	}

	public void setTepdownStatus(Integer tepdownStatus) {
		this.tepdownStatus = tepdownStatus;
	}

	public Integer getTepupStatus() {
		return tepupStatus;
	}

	public void setTepupStatus(Integer tepupStatus) {
		this.tepupStatus = tepupStatus;
	}

	public String getChangeValue() {
		return changeValue;
	}

	public void setChangeValue(String changeValue) {
		this.changeValue = changeValue;
	}
	
}


