package com.hod.pojo;
// Generated Jul 13, 2013 4:50:33 PM by Hibernate Tools 3.2.2.GA



/**
 * Hod2000DbBackupSchedule generated by hbm2java
 */
public class Hod2000DbBackupSchedule  implements java.io.Serializable {


     private Integer id  ;
     private String backupPath  ;
     private Integer completePeriod  ;
     private Integer diffTime  ;
     private String remark  ;

    public Hod2000DbBackupSchedule() {
    }

	
    public Hod2000DbBackupSchedule(Integer id) {
        this.id = id;
    }
    public Hod2000DbBackupSchedule(Integer id, String backupPath, Integer completePeriod, Integer diffTime, String remark) {
       this.id = id;
       this.backupPath = backupPath;
       this.completePeriod = completePeriod;
       this.diffTime = diffTime;
       this.remark = remark;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getBackupPath() {
        return this.backupPath;
    }
    
    public void setBackupPath(String backupPath) {
        this.backupPath = backupPath;
    }
    public Integer getCompletePeriod() {
        return this.completePeriod;
    }
    
    public void setCompletePeriod(Integer completePeriod) {
        this.completePeriod = completePeriod;
    }
    public Integer getDiffTime() {
        return this.diffTime;
    }
    
    public void setDiffTime(Integer diffTime) {
        this.diffTime = diffTime;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


