package com.hod.pojo;
// Generated Mar 29, 2013 3:52:39 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Hod2000Heatingparameter generated by hbm2java
 */
public class Hod2000Heatingparameter  implements java.io.Serializable {


     private Integer hpId  ;
     private Integer hpMonths  ;
     private Double hpFactor  ;
     private Date hpStart  ;
     private Date hpEnd  ;
     private Integer hpType;

    public Hod2000Heatingparameter() {
    }

	
    public Hod2000Heatingparameter(Integer hpId) {
        this.hpId = hpId;
    }
    public Hod2000Heatingparameter(Integer hpId, Integer hpMonths, Double hpFactor, Date hpStart, Date hpEnd,Integer hpType) {
       this.hpId = hpId;
       this.hpMonths = hpMonths;
       this.hpFactor = hpFactor;
       this.hpStart = hpStart;
       this.hpEnd = hpEnd;
       this.hpType=hpType;
    }
   
    public Integer getHpId() {
        return this.hpId;
    }
    
    public void setHpId(Integer hpId) {
        this.hpId = hpId;
    }
    public Integer getHpMonths() {
        return this.hpMonths;
    }
    
    public void setHpMonths(Integer hpMonths) {
        this.hpMonths = hpMonths;
    }
    public Double getHpFactor() {
        return this.hpFactor;
    }
    
    public void setHpFactor(Double hpFactor) {
        this.hpFactor = hpFactor;
    }
    public Date getHpStart() {
        return this.hpStart;
    }
    
    public void setHpStart(Date hpStart) {
        this.hpStart = hpStart;
    }
    public Date getHpEnd() {
        return this.hpEnd;
    }
    
    public void setHpEnd(Date hpEnd) {
        this.hpEnd = hpEnd;
    }

	public Integer getHpType() {
		return hpType;
	}

	public void setHpType(Integer hpType) {
		this.hpType = hpType;
	}
    
    



}


