package com.hod.pojo;
// Generated Feb 27, 2013 9:09:57 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Hod2000DownInfo generated by hbm2java
 */
public class Hod2000DownInfo  implements java.io.Serializable {


     private Integer downId  ;
     private String conNumber;
     private String sendContent  ;
     private String protocolType  ;
     private Date submitTime  ;
     private Integer sendFlag  ;
     private Date theDay  ;
     private Integer sendTimes  ;
     private String remark  ;
     private String meterName;

    public Hod2000DownInfo() {
    }

	
    public Hod2000DownInfo(Integer downId) {
        this.downId = downId;
    }
    public Hod2000DownInfo(Integer downId,String conNumber, String sendContent, String protocolType, Date submitTime, Integer sendFlag, Date theDay, Integer sendTimes, String remark,String meterName) {
       this.downId = downId;
       this.conNumber=conNumber;
       this.sendContent = sendContent;
       this.protocolType = protocolType;
       this.submitTime = submitTime;
       this.sendFlag = sendFlag;
       this.theDay = theDay;
       this.sendTimes = sendTimes;
       this.remark = remark;
       this.meterName=meterName;
    }
   
    public Integer getDownId() {
        return this.downId;
    }
    
    public void setDownId(Integer downId) {
        this.downId = downId;
    }
    
    public String getConNumber() {
		return conNumber;
	}


	public void setConNumber(String conNumber) {
		this.conNumber = conNumber;
	}


	public String getSendContent() {
        return this.sendContent;
    }
    
    public void setSendContent(String sendContent) {
        this.sendContent = sendContent;
    }
    public String getProtocolType() {
        return this.protocolType;
    }
    
    public void setProtocolType(String protocolType) {
        this.protocolType = protocolType;
    }
    public Date getSubmitTime() {
        return this.submitTime;
    }
    
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }
    public Integer getSendFlag() {
        return this.sendFlag;
    }
    
    public void setSendFlag(Integer sendFlag) {
        this.sendFlag = sendFlag;
    }
    public Date getTheDay() {
        return this.theDay;
    }
    
    public void setTheDay(Date theDay) {
        this.theDay = theDay;
    }
    public Integer getSendTimes() {
        return this.sendTimes;
    }
    
    public void setSendTimes(Integer sendTimes) {
        this.sendTimes = sendTimes;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

	public String getMeterName() {
		return meterName;
	}

	public void setMeterName(String meterName) {
		this.meterName = meterName;
	}
    
}


