package com.hod.pojo;
// Generated Feb 27, 2013 9:09:57 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hod2000Village generated by hbm2java
 */
public class Hod2000Village  implements java.io.Serializable {


     private Integer villageId  ;
     private String villageName  ;
     private String villageCode  ;
     private Set<Hod2000Community> hod2000Communities   = new HashSet<Hod2000Community>(0);
     private Hod2000County hod2000County  = new Hod2000County();

    public Hod2000Village() {
    }

	
    public Hod2000Village(Integer villageId, String villageName, String villageCode) {
        this.villageId = villageId;
        this.villageName = villageName;
        this.villageCode = villageCode;
    }
    public Hod2000Village(Integer villageId, String villageName, String villageCode, Set<Hod2000Community> hod2000Communities, Hod2000County hod2000County) {
       this.villageId = villageId;
       this.villageName = villageName;
       this.villageCode = villageCode;
       this.hod2000Communities = hod2000Communities;
       this.hod2000County = hod2000County;
    }
   
    public Integer getVillageId() {
        return this.villageId;
    }
    
    public void setVillageId(Integer villageId) {
        this.villageId = villageId;
    }
    public String getVillageName() {
        return this.villageName;
    }
    
    public void setVillageName(String villageName) {
        this.villageName = villageName;
    }
    public String getVillageCode() {
        return this.villageCode;
    }
    
    public void setVillageCode(String villageCode) {
        this.villageCode = villageCode;
    }
    public Set<Hod2000Community> getHod2000Communities() {
        return this.hod2000Communities;
    }
    
    public void setHod2000Communities(Set<Hod2000Community> hod2000Communities) {
        this.hod2000Communities = hod2000Communities;
    }
    public Hod2000County getHod2000County() {
        return this.hod2000County;
    }
    
    public void setHod2000County(Hod2000County hod2000County) {
        this.hod2000County = hod2000County;
    }




}


