package com.hod.pojo;
// Generated Mar 29, 2013 3:52:39 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Hod2000PreReceive generated by hbm2java
 */
public class Hod2000PreReceive  implements java.io.Serializable {


     private Integer prId  ;
     private Integer roomId  ;
     private Integer prMonths  ;
     private Double prFactor  ;
     private Double prMoney  ;
     private Integer prAfter  ;
     private Date prTime  ;
     private String prOperator;

    public Hod2000PreReceive() {
    }

	
    public Hod2000PreReceive(Integer prId, Integer roomId) {
        this.prId = prId;
        this.roomId = roomId;
    }
    public Hod2000PreReceive(Integer prId, Integer roomId, Integer prMonths, Double prFactor, Double prMoney, Integer prAfter, Date prTime,String prOperator) {
       this.prId = prId;
       this.roomId = roomId;
       this.prMonths = prMonths;
       this.prFactor = prFactor;
       this.prMoney = prMoney;
       this.prAfter = prAfter;
       this.prTime = prTime;
       this.prOperator=prOperator;
    }
   
    public Integer getPrId() {
        return this.prId;
    }
    
    public void setPrId(Integer prId) {
        this.prId = prId;
    }
   
    public Integer getRoomId() {
		return roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

    public Integer getPrMonths() {
        return this.prMonths;
    }
    
    public void setPrMonths(Integer prMonths) {
        this.prMonths = prMonths;
    }
    public Double getPrFactor() {
        return this.prFactor;
    }
    
    public void setPrFactor(Double prFactor) {
        this.prFactor = prFactor;
    }
    public Double getPrMoney() {
        return this.prMoney;
    }
    
    public void setPrMoney(Double prMoney) {
        this.prMoney = prMoney;
    }
    public Integer getPrAfter() {
        return this.prAfter;
    }
    
    public void setPrAfter(Integer prAfter) {
        this.prAfter = prAfter;
    }
    public Date getPrTime() {
        return this.prTime;
    }
    
    public void setPrTime(Date prTime) {
        this.prTime = prTime;
    }

	public String getPrOperator() {
		return prOperator;
	}

	public void setPrOperator(String prOperator) {
		this.prOperator = prOperator;
	}
}


