package com.hod.pojo;
// Generated Feb 27, 2013 9:09:57 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hod2000County generated by hbm2java
 */
public class Hod2000County  implements java.io.Serializable {


     private Integer countyId  ;
     private String countyName  ;
     private String countyCode  ;
     private Set<Hod2000Village> hod2000Villages   = new HashSet<Hod2000Village>(0);
     private Hod2000City hod2000City  = new Hod2000City();

    public Hod2000County() {
    }

	
    public Hod2000County(Integer countyId, String countyName, String countyCode) {
        this.countyId = countyId;
        this.countyName = countyName;
        this.countyCode = countyCode;
    }
    public Hod2000County(Integer countyId, String countyName, String countyCode, Set<Hod2000Village> hod2000Villages, Hod2000City hod2000City) {
       this.countyId = countyId;
       this.countyName = countyName;
       this.countyCode = countyCode;
       this.hod2000Villages = hod2000Villages;
       this.hod2000City = hod2000City;
    }
   
    public Integer getCountyId() {
        return this.countyId;
    }
    
    public void setCountyId(Integer countyId) {
        this.countyId = countyId;
    }
    public String getCountyName() {
        return this.countyName;
    }
    
    public void setCountyName(String countyName) {
        this.countyName = countyName;
    }
    public String getCountyCode() {
        return this.countyCode;
    }
    
    public void setCountyCode(String countyCode) {
        this.countyCode = countyCode;
    }
    public Set<Hod2000Village> getHod2000Villages() {
        return this.hod2000Villages;
    }
    
    public void setHod2000Villages(Set<Hod2000Village> hod2000Villages) {
        this.hod2000Villages = hod2000Villages;
    }
    public Hod2000City getHod2000City() {
        return this.hod2000City;
    }
    
    public void setHod2000City(Hod2000City hod2000City) {
        this.hod2000City = hod2000City;
    }




}


