package com.hod.pojo;
// Generated Jul 1, 2013 3:16:33 PM by Hibernate Tools 3.2.2.GA



/**
 * Hod2000DeviceInitParameter generated by hbm2java
 */
public class Hod2000DeviceInitParameter  implements java.io.Serializable {


     private Integer pid  ;
     private Integer pcol1  ;
     private Integer pcol2  ;
     private Integer pcol3  ;
     private Integer pcol4  ;
     private Integer pcol5  ;
     private Integer pcol6  ;
     private String pcol7  ;
     private String pcol8  ;
     private String pcol9  ;

    public Hod2000DeviceInitParameter() {
    }

	
    public Hod2000DeviceInitParameter(Integer pid) {
        this.pid = pid;
    }
    public Hod2000DeviceInitParameter(Integer pid, Integer pcol1, Integer pcol2, Integer pcol3, Integer pcol4, Integer pcol5, Integer pcol6, String pcol7, String pcol8, String pcol9) {
       this.pid = pid;
       this.pcol1 = pcol1;
       this.pcol2 = pcol2;
       this.pcol3 = pcol3;
       this.pcol4 = pcol4;
       this.pcol5 = pcol5;
       this.pcol6 = pcol6;
       this.pcol7 = pcol7;
       this.pcol8 = pcol8;
       this.pcol9 = pcol9;
    }
   
    public Integer getPid() {
        return this.pid;
    }
    
    public void setPid(Integer pid) {
        this.pid = pid;
    }
    public Integer getPcol1() {
        return this.pcol1;
    }
    
    public void setPcol1(Integer pcol1) {
        this.pcol1 = pcol1;
    }
    public Integer getPcol2() {
        return this.pcol2;
    }
    
    public void setPcol2(Integer pcol2) {
        this.pcol2 = pcol2;
    }
    public Integer getPcol3() {
        return this.pcol3;
    }
    
    public void setPcol3(Integer pcol3) {
        this.pcol3 = pcol3;
    }
    public Integer getPcol4() {
        return this.pcol4;
    }
    
    public void setPcol4(Integer pcol4) {
        this.pcol4 = pcol4;
    }
    public Integer getPcol5() {
        return this.pcol5;
    }
    
    public void setPcol5(Integer pcol5) {
        this.pcol5 = pcol5;
    }
    public Integer getPcol6() {
        return this.pcol6;
    }
    
    public void setPcol6(Integer pcol6) {
        this.pcol6 = pcol6;
    }
    public String getPcol7() {
        return this.pcol7;
    }
    
    public void setPcol7(String pcol7) {
        this.pcol7 = pcol7;
    }
    public String getPcol8() {
        return this.pcol8;
    }
    
    public void setPcol8(String pcol8) {
        this.pcol8 = pcol8;
    }
    public String getPcol9() {
        return this.pcol9;
    }
    
    public void setPcol9(String pcol9) {
        this.pcol9 = pcol9;
    }




}


