package com.hod.pojo;
// Generated Nov 18, 2013 3:21:54 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hod2000Unit generated by hbm2java
 */
public class Hod2000Unit  implements java.io.Serializable {


     private Integer unitId  ;
     private String unitName  ;
     private String unitCode  ;
     private String unitRemark  ;
     private Set<Hod2000Room> hod2000Rooms   = new HashSet<Hod2000Room>(0);
     private Hod2000Building hod2000Building  = new Hod2000Building();

    public Hod2000Unit() {
    }

	
    public Hod2000Unit(Integer unitId, String unitName, String unitCode) {
        this.unitId = unitId;
        this.unitName = unitName;
        this.unitCode = unitCode;
    }
    public Hod2000Unit(Integer unitId, String unitName, String unitCode, String unitRemark, Set<Hod2000Room> hod2000Rooms, Hod2000Building hod2000Building) {
       this.unitId = unitId;
       this.unitName = unitName;
       this.unitCode = unitCode;
       this.unitRemark = unitRemark;
       this.hod2000Rooms = hod2000Rooms;
       this.hod2000Building = hod2000Building;
    }
   
    public Integer getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }
    public String getUnitName() {
        return this.unitName;
    }
    
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }
    public String getUnitCode() {
        return this.unitCode;
    }
    
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode;
    }
    public String getUnitRemark() {
        return this.unitRemark;
    }
    
    public void setUnitRemark(String unitRemark) {
        this.unitRemark = unitRemark;
    }
    public Set<Hod2000Room> getHod2000Rooms() {
        return this.hod2000Rooms;
    }
    
    public void setHod2000Rooms(Set<Hod2000Room> hod2000Rooms) {
        this.hod2000Rooms = hod2000Rooms;
    }
    public Hod2000Building getHod2000Building() {
        return this.hod2000Building;
    }
    
    public void setHod2000Building(Hod2000Building hod2000Building) {
        this.hod2000Building = hod2000Building;
    }




}


