package com.hod.pojo;
// Generated Dec 4, 2013 10:08:40 AM by Hibernate Tools 3.2.2.GA



/**
 * Hod2000BatchClientError generated by hbm2java
 */
public class Hod2000BatchClientError  implements java.io.Serializable {


     private Integer id  ;
     private String errorMsg  ;
     private String clientName  ;
     private String clientSex  ;
     private String clientCardType  ;
     private String clientCardNumber  ;
     private String clientAddress  ;
     private String clientTel  ;
     private String ptype  ;
     private String roomAddress  ;
     private String roomRemark  ;

    public Hod2000BatchClientError() {
    }

	
    public Hod2000BatchClientError(Integer id) {
        this.id = id;
    }
    public Hod2000BatchClientError(Integer id, String errorMsg, String clientName, String clientSex, String clientCardType, String clientCardNumber, String clientAddress, String clientTel, String ptype, String roomAddress, String roomRemark) {
       this.id = id;
       this.errorMsg = errorMsg;
       this.clientName = clientName;
       this.clientSex = clientSex;
       this.clientCardType = clientCardType;
       this.clientCardNumber = clientCardNumber;
       this.clientAddress = clientAddress;
       this.clientTel = clientTel;
       this.ptype = ptype;
       this.roomAddress = roomAddress;
       this.roomRemark = roomRemark;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getErrorMsg() {
        return this.errorMsg;
    }
    
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
    }
    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }
    public String getClientSex() {
        return this.clientSex;
    }
    
    public void setClientSex(String clientSex) {
        this.clientSex = clientSex;
    }
    public String getClientCardType() {
        return this.clientCardType;
    }
    
    public void setClientCardType(String clientCardType) {
        this.clientCardType = clientCardType;
    }
    public String getClientCardNumber() {
        return this.clientCardNumber;
    }
    
    public void setClientCardNumber(String clientCardNumber) {
        this.clientCardNumber = clientCardNumber;
    }
    public String getClientAddress() {
        return this.clientAddress;
    }
    
    public void setClientAddress(String clientAddress) {
        this.clientAddress = clientAddress;
    }
    public String getClientTel() {
        return this.clientTel;
    }
    
    public void setClientTel(String clientTel) {
        this.clientTel = clientTel;
    }
    public String getPtype() {
        return this.ptype;
    }
    
    public void setPtype(String ptype) {
        this.ptype = ptype;
    }
    public String getRoomAddress() {
        return this.roomAddress;
    }
    
    public void setRoomAddress(String roomAddress) {
        this.roomAddress = roomAddress;
    }
    public String getRoomRemark() {
        return this.roomRemark;
    }
    
    public void setRoomRemark(String roomRemark) {
        this.roomRemark = roomRemark;
    }


}


