package com.hod.pojo;
// Generated Feb 27, 2013 9:09:57 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Hod2000MeterInfoTemp generated by hbm2java
 */
public class Hod2000MeterInfoTemp  implements java.io.Serializable {


     private Integer tid  ;
     private String meterName  ;
     private String currentEnergy  ;
     private String accumulateFlow  ;
     private String meterFlow  ;
     private Integer accumulateTime  ;
     private String supplyTemper  ;
     private String backTemper  ;
     private Date readTime  ;

    public Hod2000MeterInfoTemp() {
    }

	
    public Hod2000MeterInfoTemp(Integer tid) {
        this.tid = tid;
    }
    public Hod2000MeterInfoTemp(Integer tid, String meterName, String currentEnergy, String accumulateFlow, String meterFlow,Integer accumulateTime, String supplyTemper, String backTemper, Date readTime) {
       this.tid = tid;
       this.meterName = meterName;
       this.currentEnergy = currentEnergy;
       this.accumulateFlow = accumulateFlow;
       this.meterFlow = meterFlow;
       this.accumulateTime = accumulateTime;
       this.supplyTemper = supplyTemper;
       this.backTemper = backTemper;
       this.readTime = readTime;
    }
   
    public Integer getTid() {
        return this.tid;
    }
    
    public void setTid(Integer tid) {
        this.tid = tid;
    }
    public String getMeterName() {
        return this.meterName;
    }
    
    public void setMeterName(String meterName) {
        this.meterName = meterName;
    }
    public String getCurrentEnergy() {
        return this.currentEnergy;
    }
    
    public void setCurrentEnergy(String currentEnergy) {
        this.currentEnergy = currentEnergy;
    }
    public String getAccumulateFlow() {
        return this.accumulateFlow;
    }
    
    public void setAccumulateFlow(String accumulateFlow) {
        this.accumulateFlow = accumulateFlow;
    }
    public String getMeterFlow() {
        return this.meterFlow;
    }
    
    public void setMeterFlow(String meterFlow) {
        this.meterFlow = meterFlow;
    }
    public Integer getAccumulateTime() {
        return this.accumulateTime;
    }
    
    public void setAccumulateTime(Integer accumulateTime) {
        this.accumulateTime = accumulateTime;
    }
    public String getSupplyTemper() {
        return this.supplyTemper;
    }
    
    public void setSupplyTemper(String supplyTemper) {
        this.supplyTemper = supplyTemper;
    }
    public String getBackTemper() {
        return this.backTemper;
    }
    
    public void setBackTemper(String backTemper) {
        this.backTemper = backTemper;
    }
    public Date getReadTime() {
        return this.readTime;
    }
    
    public void setReadTime(Date readTime) {
        this.readTime = readTime;
    }




}


