package com.hod.pojo;
// Generated Feb 27, 2013 9:09:57 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hod2000Room generated by hbm2java
 */
public class Hod2000Room  implements java.io.Serializable,Comparable {


     private Integer roomId  ;
     private String roomName  ;
     private String roomCode  ;
     private String roomRemark;
     private String roomHouseType;
     private double roomSize;
     private Integer priceType;
     private Integer roomPreFlag;
     private Integer roomReceiveFlag;
     private Hod2000Client hod2000Client  = new Hod2000Client();
     private Set<Hod2000Meter> hod2000Meters   = new HashSet<Hod2000Meter>(0);
     private Hod2000Unit hod2000Unit  = new Hod2000Unit();

    public Hod2000Room() {
    }

	
    public Hod2000Room(Integer roomId, String roomName, String roomCode,String roomRemark,String roomHouseType,double roomSize,Integer priceType,Integer roomPreFlag,Integer roomReceiveFlag) {
        this.roomId = roomId;
        this.roomName = roomName;
        this.roomCode = roomCode;
        this.roomHouseType=roomHouseType;
        this.roomRemark=roomRemark;
        this.roomSize=roomSize;
        this.priceType=priceType;
        this.roomPreFlag=roomPreFlag;
        this.roomReceiveFlag=roomReceiveFlag;
    }
    public Hod2000Room(Integer roomId, String roomName, String roomCode,String roomRemark,String roomHouseType,double roomSize,Integer priceType,Integer roomPreFlag,Integer roomReceiveFlag, Hod2000Client hod2000Client, Set<Hod2000Meter> hod2000Meters, Hod2000Unit hod2000Unit) {
       this.roomId = roomId;
       this.roomName = roomName;
       this.roomCode = roomCode;
       this.roomHouseType=roomHouseType;
       this.roomRemark=roomRemark;
       this.roomSize=roomSize;
       this.priceType=priceType;
       this.roomPreFlag=roomPreFlag;
       this.roomReceiveFlag=roomReceiveFlag;
       this.hod2000Client = hod2000Client;
       this.hod2000Meters = hod2000Meters;
       this.hod2000Unit = hod2000Unit;
    }
   
    public Integer getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }
    public String getRoomName() {
        return this.roomName;
    }
    
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }
    public String getRoomCode() {
        return this.roomCode;
    }
    
    public void setRoomCode(String roomCode) {
        this.roomCode = roomCode;
    }
    public Hod2000Client getHod2000Client() {
        return this.hod2000Client;
    }
    
    public void setHod2000Client(Hod2000Client hod2000Client) {
        this.hod2000Client = hod2000Client;
    }
    public Set<Hod2000Meter> getHod2000Meters() {
        return this.hod2000Meters;
    }
    
    public void setHod2000Meters(Set<Hod2000Meter> hod2000Meters) {
        this.hod2000Meters = hod2000Meters;
    }
    public Hod2000Unit getHod2000Unit() {
        return this.hod2000Unit;
    }
    
    public void setHod2000Unit(Hod2000Unit hod2000Unit) {
        this.hod2000Unit = hod2000Unit;
    }


	public String getRoomRemark() {
		return roomRemark;
	}


	public void setRoomRemark(String roomRemark) {
		this.roomRemark = roomRemark;
	}


	public String getRoomHouseType() {
		return roomHouseType;
	}


	public void setRoomHouseType(String roomHouseType) {
		this.roomHouseType = roomHouseType;
	}


	public double getRoomSize() {
		return roomSize;
	}


	public void setRoomSize(double roomSize) {
		this.roomSize = roomSize;
	}


	public Integer getPriceType() {
		return priceType;
	}


	public void setPriceType(Integer priceType) {
		this.priceType = priceType;
	}


	public int compareTo(Object arg0) {
		Hod2000Room o = (Hod2000Room)arg0;
		if(Integer.parseInt(this.getRoomCode())>Integer.parseInt(o.getRoomCode())){
			return -1;
		}else if(Integer.parseInt(this.getRoomCode())<Integer.parseInt(o.getRoomCode())){
			return 1;
		}else{
			return 0;
		}
	}

	public Integer getRoomPreFlag() {
		return roomPreFlag;
	}

	public void setRoomPreFlag(Integer roomPreFlag) {
		this.roomPreFlag = roomPreFlag;
	}

	public Integer getRoomReceiveFlag() {
		return roomReceiveFlag;
	}

	public void setRoomReceiveFlag(Integer roomReceiveFlag) {
		this.roomReceiveFlag = roomReceiveFlag;
	}
	
	
}


