package com.hod.pojo;
// Generated Feb 27, 2013 9:09:57 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hod2000Building generated by hbm2java
 */
public class Hod2000Building  implements java.io.Serializable,Comparable{


	private Integer buildingId  ;
     private String buildingName  ;
     private String buildingCode  ;
     private String buildingLongitude  ;
     private String buildingLatitude  ;
     private String buildingRemark;
     private Hod2000Community hod2000Community  = new Hod2000Community();
     private Set<Hod2000Unit> hod2000Units   = new HashSet<Hod2000Unit>(0);

    public Hod2000Building() {
    }

	
    public Hod2000Building(Integer buildingId, String buildingName, String buildingCode, String buildingLongitude,String buildingRemark) {
        this.buildingId = buildingId;
        this.buildingName = buildingName;
        this.buildingCode = buildingCode;
        this.buildingLongitude = buildingLongitude;
        this.buildingRemark=buildingRemark;
    }
    public Hod2000Building(Integer buildingId, String buildingName, String buildingCode, String buildingLongitude, String buildingLatitude,String buildingRemark, Hod2000Community hod2000Community, Set<Hod2000Unit> hod2000Units) {
       this.buildingId = buildingId;
       this.buildingName = buildingName;
       this.buildingCode = buildingCode;
       this.buildingLongitude = buildingLongitude;
       this.buildingLatitude = buildingLatitude;
       this.buildingRemark=buildingRemark;
       this.hod2000Community = hod2000Community;
       this.hod2000Units = hod2000Units;
    }
   
    public Integer getBuildingId() {
        return this.buildingId;
    }
    
    public void setBuildingId(Integer buildingId) {
        this.buildingId = buildingId;
    }
    public String getBuildingName() {
        return this.buildingName;
    }
    
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName;
    }
    public String getBuildingCode() {
        return this.buildingCode;
    }
    
    public void setBuildingCode(String buildingCode) {
        this.buildingCode = buildingCode;
    }
    public String getBuildingLongitude() {
        return this.buildingLongitude;
    }
    
    public void setBuildingLongitude(String buildingLongitude) {
        this.buildingLongitude = buildingLongitude;
    }
    public String getBuildingLatitude() {
        return this.buildingLatitude;
    }
    
    public void setBuildingLatitude(String buildingLatitude) {
        this.buildingLatitude = buildingLatitude;
    }
    public Hod2000Community getHod2000Community() {
        return this.hod2000Community;
    }
    
    public void setHod2000Community(Hod2000Community hod2000Community) {
        this.hod2000Community = hod2000Community;
    }
    public Set<Hod2000Unit> getHod2000Units() {
        return this.hod2000Units;
    }
    
    public void setHod2000Units(Set<Hod2000Unit> hod2000Units) {
        this.hod2000Units = hod2000Units;
    }


	public String getBuildingRemark() {
		return buildingRemark;
	}


	public void setBuildingRemark(String buildingRemark) {
		this.buildingRemark = buildingRemark;
	}
    

    public int compareTo(Object arg0) {
		// TODO Auto-generated method stub
    	Hod2000Building o =(Hod2000Building)arg0;
    	if(Integer.parseInt(this.getBuildingCode())>Integer.parseInt(o.getBuildingCode())){
			return -1;
		}else if(Integer.parseInt(this.getBuildingCode())<Integer.parseInt(o.getBuildingCode())){
			return 1;
		}else{
			return 0;
		}
	}


}


