package com.hod.pojo;
// Generated Feb 27, 2013 9:09:57 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Hod2000OperateLog generated by hbm2java
 */
public class Hod2000OperateLog  implements java.io.Serializable {


     private Integer logId  ;
     private String operName  ;
     private Date logDate  ;
     private String logContent  ;

    public Hod2000OperateLog() {
    }

	
    public Hod2000OperateLog(Integer logId) {
        this.logId = logId;
    }
    public Hod2000OperateLog(Integer logId, String operName, Date logDate, String logContent) {
       this.logId = logId;
       this.operName = operName;
       this.logDate = logDate;
       this.logContent = logContent;
    }
   
    public Integer getLogId() {
        return this.logId;
    }
    
    public void setLogId(Integer logId) {
        this.logId = logId;
    }
    public String getOperName() {
        return this.operName;
    }
    
    public void setOperName(String operName) {
        this.operName = operName;
    }
    public Date getLogDate() {
        return this.logDate;
    }
    
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }
    public String getLogContent() {
        return this.logContent;
    }
    
    public void setLogContent(String logContent) {
        this.logContent = logContent;
    }




}


