package com.hod.pojo;
// Generated Feb 27, 2013 9:09:57 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hod2000City generated by hbm2java
 */
public class Hod2000City  implements java.io.Serializable {


     private Integer cityId  ;
     private String cityName  ;
     private String cityCode  ;
     private Hod2000Region hod2000Region  = new Hod2000Region();
     private Set<Hod2000County> hod2000Counties   = new HashSet<Hod2000County>(0);

    public Hod2000City() {
    }

	
    public Hod2000City(Integer cityId, String cityName, String cityCode) {
        this.cityId = cityId;
        this.cityName = cityName;
        this.cityCode = cityCode;
    }
    public Hod2000City(Integer cityId, String cityName, String cityCode, Hod2000Region hod2000Region, Set<Hod2000County> hod2000Counties) {
       this.cityId = cityId;
       this.cityName = cityName;
       this.cityCode = cityCode;
       this.hod2000Region = hod2000Region;
       this.hod2000Counties = hod2000Counties;
    }
   
    public Integer getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public String getCityCode() {
        return this.cityCode;
    }
    
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }
    public Hod2000Region getHod2000Region() {
        return this.hod2000Region;
    }
    
    public void setHod2000Region(Hod2000Region hod2000Region) {
        this.hod2000Region = hod2000Region;
    }
    public Set<Hod2000County> getHod2000Counties() {
        return this.hod2000Counties;
    }
    
    public void setHod2000Counties(Set<Hod2000County> hod2000Counties) {
        this.hod2000Counties = hod2000Counties;
    }




}


