package com.hod.pojo;
// Generated Jun 25, 2013 3:59:34 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Hod2000ParaDownInfoCache generated by hbm2java
 */
public class Hod2000ParaDownInfoCache  implements java.io.Serializable {


     private Integer downId  ;
     private String conNum  ;
     private String sendContent  ;
     private String protocolType  ;
     private Date submitTime  ;
     private Integer sendFlag  ;
     private Integer state  ;
     private String remark  ;

    public Hod2000ParaDownInfoCache() {
    }

	
    public Hod2000ParaDownInfoCache(Integer downId) {
        this.downId = downId;
    }
    public Hod2000ParaDownInfoCache(Integer downId, String conNum, String sendContent, String protocolType, Date submitTime, Integer sendFlag, Integer state, String remark) {
       this.downId = downId;
       this.conNum = conNum;
       this.sendContent = sendContent;
       this.protocolType = protocolType;
       this.submitTime = submitTime;
       this.sendFlag = sendFlag;
       this.state = state;
       this.remark = remark;
    }
   
    public Integer getDownId() {
        return this.downId;
    }
    
    public void setDownId(Integer downId) {
        this.downId = downId;
    }
   
    public String getConNum() {
		return conNum;
	}

	public void setConNum(String conNum) {
		this.conNum = conNum;
	}

	public String getSendContent() {
        return this.sendContent;
    }
    
    public void setSendContent(String sendContent) {
        this.sendContent = sendContent;
    }
    public String getProtocolType() {
        return this.protocolType;
    }
    
    public void setProtocolType(String protocolType) {
        this.protocolType = protocolType;
    }
    public Date getSubmitTime() {
        return this.submitTime;
    }
    
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }
    public Integer getSendFlag() {
        return this.sendFlag;
    }
    
    public void setSendFlag(Integer sendFlag) {
        this.sendFlag = sendFlag;
    }
    public Integer getState() {
        return this.state;
    }
    
    public void setState(Integer state) {
        this.state = state;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


