package com.hod.pojo;

/**
 * Hod2000MeterCallDownInfo generated by hbm2java
 * 
 * @author öÄÓÂ½ð
 * @May 22, 2013 11:49:28 AM
 * @version V0.1
 */

public class Hod2000MeterCallDownInfo implements java.io.Serializable{
	
    private Integer callId;
    private String meterName;
    private String conNum;
    private String sendContent;
    private String protocolType;
    private String submitTime;
    private Integer sendFlag;
    private Integer state;
    private String resultContent;
    private String resultAccuFlow;
    private String remark;
    
    public Hod2000MeterCallDownInfo(Integer callId,String meterName,String conNum,String sendContent,String protocolType,String submitTime,Integer sendFlag,Integer state,String remark,String resultContent,String resultAccuFlow){
    	this.callId = callId;
    	this.meterName = meterName;
    	this.conNum = conNum;
    	this.sendContent = sendContent;
    	this.protocolType = protocolType;
    	this.submitTime = submitTime;
    	this.sendFlag = sendFlag;
    	this.state = state;
    	this.resultAccuFlow = resultAccuFlow;
    	this.resultContent = resultContent;
    	this.remark = remark;
    }

	public Hod2000MeterCallDownInfo() {
		// TODO Auto-generated constructor stub
	}

	public Integer getCallId() {
		return callId;
	}

	public void setCallId(Integer callId) {
		this.callId = callId;
	}

	public String getMeterName() {
		return meterName;
	}

	public void setMeterName(String meterName) {
		this.meterName = meterName;
	}

	public String getConNum() {
		return conNum;
	}

	public void setConNum(String conNum) {
		this.conNum = conNum;
	}

	public String getSendContent() {
		return sendContent;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setSendContent(String sendContent) {
		this.sendContent = sendContent;
	}

	public String getProtocolType() {
		return protocolType;
	}

	public void setProtocolType(String protocolType) {
		this.protocolType = protocolType;
	}

	public String getSubmitTime() {
		return submitTime;
	}

	public void setSubmitTime(String submitTime) {
		this.submitTime = submitTime;
	}

	public Integer getSendFlag() {
		return sendFlag;
	}

	public void setSendFlag(Integer sendFlag) {
		this.sendFlag = sendFlag;
	}

	public Integer getState() {
		return state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public String getResultContent() {
		return resultContent;
	}

	public void setResultContent(String resultContent) {
		this.resultContent = resultContent;
	}

	public String getResultAccuFlow() {
		return resultAccuFlow;
	}

	public void setResultAccuFlow(String resultAccuFlow) {
		this.resultAccuFlow = resultAccuFlow;
	}

}
