package com.hod.pojo;
// Generated Feb 27, 2013 9:09:57 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hod2000Concentrator generated by hbm2java
 */
public class Hod2000Concentrator  implements java.io.Serializable,Comparable {


     private Integer conId  ;
     private String conNumber  ;
     private Integer freezeInterval  ;
     private Integer freezeIntervalValue;
     private Integer clearDate;
     private String conAddress  ;
     private String conPositionName;
     private String conCompanyNum  ;
     private String conDeviceNum  ;
     private String conSoftVersion  ;
     private String conSoftDate  ;
     private String conCapacityInfoCode  ;
     private String conProtocolVersion  ;
     private String conHardVersion  ;
     private String conHardDate  ;
     private Integer conIsonline;
     private Integer conFlashStatus;
     private Integer conLastPosition;
     private Integer masterConId;
     private String typeIndexs;
     private Integer conRfValue;
     private Integer conCom1Status;
     private Integer conCom2Status;
     private Integer conCom3Status;
     private Integer conAble;
     private Integer conStrong;
     private Set<Hod2000Meter> hod2000Meters   = new HashSet<Hod2000Meter>(0);

    public Hod2000Concentrator() {
    }

	
    public Hod2000Concentrator(Integer conId) {
        this.conId = conId;
    }
    public Hod2000Concentrator(Integer conId, String conNumber, Integer freezeInterval,Integer freezeIntervalValue,Integer clearDate, String conAddress,String conPositionName, Integer conIsonline,Integer conFlashStatus, Set<Hod2000Meter> hod2000Meters,String conCompanyNum, String conDeviceNum, String conSoftVersion, String conSoftDate, String conCapacityInfoCode, String conProtocolVersion, String conHardVersion, String conHardDate,Integer conLastPosition,Integer masterConId,String typeIndexs,Integer conRfValue,Integer conCom1Status,Integer conCom2Status,Integer conCom3Status,Integer conAble,Integer conStrong) {
       this.conId = conId;
       this.conNumber = conNumber;
       this.freezeInterval = freezeInterval;
       this.freezeIntervalValue=freezeIntervalValue;
       this.clearDate=clearDate;
       this.conAddress = conAddress;
       this.conPositionName=conPositionName;
       this.hod2000Meters = hod2000Meters;
       this.conCompanyNum = conCompanyNum;
       this.conDeviceNum = conDeviceNum;
       this.conSoftVersion = conSoftVersion;
       this.conSoftDate = conSoftDate;
       this.conCapacityInfoCode = conCapacityInfoCode;
       this.conProtocolVersion = conProtocolVersion;
       this.conHardVersion = conHardVersion;
       this.conHardDate = conHardDate;
       this.conIsonline = conIsonline;
       this.conFlashStatus=conFlashStatus;
       this.conLastPosition = conLastPosition;
       this.masterConId=masterConId;
       this.typeIndexs=typeIndexs;
       this.conRfValue=conRfValue;
       this.conCom1Status=conCom1Status;
       this.conCom2Status=conCom2Status;
       this.conCom3Status=conCom3Status;
       this.conAble=conAble;
       this.conStrong=conStrong;
    }
   
    public Integer getConId() {
        return this.conId;
    }
    
    public void setConId(Integer conId) {
        this.conId = conId;
    }
    
    public Integer getConLastPosition() {
		return conLastPosition;
	}

	public void setConLastPosition(Integer conLastPosition) {
		this.conLastPosition = conLastPosition;
	}


	public String getConNumber() {
        return this.conNumber;
    }
    
    public void setConNumber(String conNumber) {
        this.conNumber = conNumber;
    }
    public Integer getFreezeInterval() {
        return this.freezeInterval;
    }
    
    public void setFreezeInterval(Integer freezeInterval) {
        this.freezeInterval = freezeInterval;
    }
    
    public Integer getFreezeIntervalValue() {
		return freezeIntervalValue;
	}

	public void setFreezeIntervalValue(Integer freezeIntervalValue) {
		this.freezeIntervalValue = freezeIntervalValue;
	}

	public String getConAddress() {
        return this.conAddress;
    }
    
    public void setConAddress(String conAddress) {
        this.conAddress = conAddress;
    }
    public Set<Hod2000Meter> getHod2000Meters() {
        return this.hod2000Meters;
    }
    
    public void setHod2000Meters(Set<Hod2000Meter> hod2000Meters) {
        this.hod2000Meters = hod2000Meters;
    }
    
	public String getConCompanyNum() {
		return conCompanyNum;
	}


	public void setConCompanyNum(String conCompanyNum) {
		this.conCompanyNum = conCompanyNum;
	}


	public String getConDeviceNum() {
		return conDeviceNum;
	}


	public void setConDeviceNum(String conDeviceNum) {
		this.conDeviceNum = conDeviceNum;
	}


	public String getConSoftVersion() {
		return conSoftVersion;
	}


	public void setConSoftVersion(String conSoftVersion) {
		this.conSoftVersion = conSoftVersion;
	}


	public String getConSoftDate() {
		return conSoftDate;
	}


	public void setConSoftDate(String conSoftDate) {
		this.conSoftDate = conSoftDate;
	}


	public String getConCapacityInfoCode() {
		return conCapacityInfoCode;
	}


	public void setConCapacityInfoCode(String conCapacityInfoCode) {
		this.conCapacityInfoCode = conCapacityInfoCode;
	}


	public String getConProtocolVersion() {
		return conProtocolVersion;
	}


	public void setConProtocolVersion(String conProtocolVersion) {
		this.conProtocolVersion = conProtocolVersion;
	}


	public String getConHardVersion() {
		return conHardVersion;
	}


	public void setConHardVersion(String conHardVersion) {
		this.conHardVersion = conHardVersion;
	}

	public String getConHardDate() {
		return conHardDate;
	}

	public void setConHardDate(String conHardDate) {
		this.conHardDate = conHardDate;
	}

	public Integer getConIsonline() {
		return conIsonline;
	}

	public void setConIsonline(Integer conIsonline) {
		this.conIsonline = conIsonline;
	}
	
	public Integer getConFlashStatus() {
		return conFlashStatus;
	}


	public void setConFlashStatus(Integer conFlashStatus) {
		this.conFlashStatus = conFlashStatus;
	}


	public Integer getClearDate() {
		return clearDate;
	}

	public void setClearDate(Integer clearDate) {
		this.clearDate = clearDate;
	}

	public String getConPositionName() {
		return conPositionName;
	}

	public void setConPositionName(String conPositionName) {
		this.conPositionName = conPositionName;
	}

	public Integer getMasterConId() {
		return masterConId;
	}

	public void setMasterConId(Integer masterConId) {
		this.masterConId = masterConId;
	}

	public String getTypeIndexs() {
		return typeIndexs;
	}

	public void setTypeIndexs(String typeIndexs) {
		this.typeIndexs = typeIndexs;
	}

	public Integer getConRfValue() {
		return conRfValue;
	}

	public void setConRfValue(Integer conRfValue) {
		this.conRfValue = conRfValue;
	}
	
	public Integer getConCom1Status() {
		return conCom1Status;
	}

	public void setConCom1Status(Integer conCom1Status) {
		this.conCom1Status = conCom1Status;
	}

	public Integer getConCom2Status() {
		return conCom2Status;
	}

	public void setConCom2Status(Integer conCom2Status) {
		this.conCom2Status = conCom2Status;
	}

	public Integer getConCom3Status() {
		return conCom3Status;
	}
	
	public void setConCom3Status(Integer conCom3Status) {
		this.conCom3Status = conCom3Status;
	}
	
	public Integer getConAble() {
		return conAble;
	}

	public void setConAble(Integer conAble) {
		this.conAble = conAble;
	}
	
	public Integer getConStrong() {
		return conStrong;
	}

	public void setConStrong(Integer conStrong) {
		this.conStrong = conStrong;
	}

	public int compareTo(Object arg0) {
		// TODO Auto-generated method stub
		Hod2000Concentrator o = (Hod2000Concentrator)arg0;
		if(this.getConId()>o.getConId()){
			return -1;
		}else if(this.getConId()<o.getConId()){
			return 1;
		}else{
			return 0;
		}
	}
}


