package com.hod.pojo;
// Generated Feb 27, 2013 9:09:57 AM by Hibernate Tools 3.2.2.GA



/**
 * Hod2000Permission generated by hbm2java
 */
public class Hod2000Permission  implements java.io.Serializable {


     private Integer permId  ;
     private String permName  ;
     private String permCodeName  ;

    public Hod2000Permission() {
    }

	
    public Hod2000Permission(Integer permId) {
        this.permId = permId;
    }
    public Hod2000Permission(Integer permId, String permName, String permCodeName) {
       this.permId = permId;
       this.permName = permName;
       this.permCodeName = permCodeName;
    }
   
    public Integer getPermId() {
        return this.permId;
    }
    
    public void setPermId(Integer permId) {
        this.permId = permId;
    }
    public String getPermName() {
        return this.permName;
    }
    
    public void setPermName(String permName) {
        this.permName = permName;
    }
    public String getPermCodeName() {
        return this.permCodeName;
    }
    
    public void setPermCodeName(String permCodeName) {
        this.permCodeName = permCodeName;
    }
}


