package com.hod.pojo;
// Generated Feb 27, 2013 9:09:57 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hod2000Region generated by hbm2java
 */
public class Hod2000Region  implements java.io.Serializable {


     private Integer regionId  ;
     private String regionName  ;
     private String regionCode  ;
     private Set<Hod2000City> hod2000Cities   = new HashSet<Hod2000City>(0);

    public Hod2000Region() {
    }

	
    public Hod2000Region(Integer regionId, String regionName, String regionCode) {
        this.regionId = regionId;
        this.regionName = regionName;
        this.regionCode = regionCode;
    }
    public Hod2000Region(Integer regionId, String regionName, String regionCode, Set<Hod2000City> hod2000Cities) {
       this.regionId = regionId;
       this.regionName = regionName;
       this.regionCode = regionCode;
       this.hod2000Cities = hod2000Cities;
    }
   
    public Integer getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }
    public String getRegionName() {
        return this.regionName;
    }
    
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }
    public String getRegionCode() {
        return this.regionCode;
    }
    
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode;
    }
    public Set<Hod2000City> getHod2000Cities() {
        return this.hod2000Cities;
    }
    
    public void setHod2000Cities(Set<Hod2000City> hod2000Cities) {
        this.hod2000Cities = hod2000Cities;
    }




}


