package com.hod.pojo;
// Generated Mar 13, 2013 4:36:39 PM by Hibernate Tools 3.2.2.GA



/**
 * Hod2000PriceDetail generated by hbm2java
 */
public class Hod2000PriceDetail  implements java.io.Serializable {


     private Integer pdId  ;
     private Double pdBasePrice  ;
     private Double pdPowerPrice  ;
     private Double pdPower  ;
     private Hod2000Price hod2000Price  = new Hod2000Price();

    public Hod2000PriceDetail() {
    }

	
    public Hod2000PriceDetail(Integer pdId) {
        this.pdId = pdId;
    }
    public Hod2000PriceDetail(Integer pdId, Double pdBasePrice, Double pdPowerPrice, Double pdPower, Hod2000Price hod2000Price) {
       this.pdId = pdId;
       this.pdBasePrice = pdBasePrice;
       this.pdPowerPrice = pdPowerPrice;
       this.pdPower = pdPower;
       this.hod2000Price = hod2000Price;
    }
   
    public Integer getPdId() {
        return this.pdId;
    }
    
    public void setPdId(Integer pdId) {
        this.pdId = pdId;
    }
    public Double getPdBasePrice() {
        return this.pdBasePrice;
    }
    
    public void setPdBasePrice(Double pdBasePrice) {
        this.pdBasePrice = pdBasePrice;
    }
    public Double getPdPowerPrice() {
        return this.pdPowerPrice;
    }
    
    public void setPdPowerPrice(Double pdPowerPrice) {
        this.pdPowerPrice = pdPowerPrice;
    }
    public Double getPdPower() {
        return this.pdPower;
    }
    
    public void setPdPower(Double pdPower) {
        this.pdPower = pdPower;
    }
    public Hod2000Price getHod2000Price() {
        return this.hod2000Price;
    }
    
    public void setHod2000Price(Hod2000Price hod2000Price) {
        this.hod2000Price = hod2000Price;
    }




}


