package com.hod.pojo;
// Generated Feb 27, 2013 9:09:57 AM by Hibernate Tools 3.2.2.GA



/**
 * Hod2000Operator generated by hbm2java
 */
public class Hod2000Operator  implements java.io.Serializable {


     private Integer operId  ;
     private String loginName  ;
     private String operPassword  ;
     private Integer operEnable  ;
     private Hod2000Role hod2000Role  = new Hod2000Role();

    public Hod2000Operator() {
    }

	
    public Hod2000Operator(Integer operId) {
        this.operId = operId;
    }
    public Hod2000Operator(Integer operId, String loginName, String operPassword, Integer operEnable, Hod2000Role hod2000Role) {
       this.operId = operId;
       this.loginName = loginName;
       this.operPassword = operPassword;
       this.operEnable = operEnable;
       this.hod2000Role = hod2000Role;
    }
   
    public Integer getOperId() {
        return this.operId;
    }
    
    public void setOperId(Integer operId) {
        this.operId = operId;
    }
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }
    public String getOperPassword() {
        return this.operPassword;
    }
    
    public void setOperPassword(String operPassword) {
        this.operPassword = operPassword;
    }
    public Integer getOperEnable() {
        return this.operEnable;
    }
    
    public void setOperEnable(Integer operEnable) {
        this.operEnable = operEnable;
    }


	public Hod2000Role getHod2000Role() {
		return hod2000Role;
	}


	public void setHod2000Role(Hod2000Role hod2000Role) {
		this.hod2000Role = hod2000Role;
	}
   




}


